### ISSUE TITLE
Latest update broke the app

### ISSUE THREAD

**Issue by PurpleCodingWizard** [afonsotrepa/PocketGopher#9]
v1.25 removes the option to run the app(test in fdroid) and doesn't show in the launcher either.
Plus the new open gopher link crashes the app.
v1.24 doesn't have these issues.

Gopher links tested from here: http://www.ucc.asn.au/~alastair/gopher.html

**Comment by marcnause** [comment]
I am terribly sorry. The problem seems to have been caused by a change I made in the manifest of the app. I have created a new pull request which hopefully fixes the issue. I have tested by creating an APK and installing it manually on my device. The issue did not appear when I made the original change and tested it by deploying it via Android Studio.

**Comment by xxzozaxx** [comment]
When will the app comes back ?

**Comment by marcnause** [comment]
I have created an issue for F-Droid: https://gitlab.com/fdroid/fdroiddata/issues/1662

I will also mention @afonsotrepa here and hope that this will trigger an email.
